In [40]:
import pandas as pd

with open('data/age_data.json','w+') as f:
  ages = pd.read_csv('data/age_data.csv', header=0, names=['value', 'cases', 'Case count', 'deaths', 'Death count', 'pop', 'dc_ratio'])
  ages = ages[['value', 'pop', 'cases', 'deaths', 'dc_ratio']]
  ages[['cases', 'deaths', 'dc_ratio']] = ages[['cases', 'deaths', 'dc_ratio']]*100
  ages = ages.append({'value':'-', 'pop':0, 'cases':0, 'deaths':0, 'dc_ratio':0},ignore_index=True)
  f.write(f'{{ "age_data": {ages.to_json(orient="records")} }}')
  f.close()

with open('data/sex_data.json','w+') as f:
  sexes = pd.read_csv('data/sex_data.csv', header=0, names=['value', 'cases', 'Case count', 'deaths', 'Death Range', 'Death count', 'pop', 'dc_ratio'])
  sexes = sexes[['value', 'pop', 'cases', 'deaths', 'dc_ratio']]
  sexes['pop'] = sexes['pop']
  sexes[['cases', 'deaths', 'dc_ratio']] = sexes[['cases', 'deaths', 'dc_ratio']]*10000
  sexes = sexes.append({'value':'-', 'pop':0, 'cases':0, 'deaths':0, 'dc_ratio':0},ignore_index=True)
  f.write(f'{{ "sex_data": {sexes.to_json(orient="records")} }}')
  f.close()


with open('data/ethnicity_data.json','w+') as f:
  races = pd.read_csv('data/ethnicity_data.csv', header=0, names=['value', 'cases', 'Case count', 'pop', 'deaths', 'Death count',  'dc_ratio'])
  races = races[['value', 'pop', 'cases', 'deaths', 'dc_ratio']]
  races[['cases', 'deaths', 'dc_ratio']] = races[['cases', 'deaths', 'dc_ratio']]*10000
  races = races.append({'value':'-', 'pop':0, 'cases':0, 'deaths':0, 'dc_ratio':0},ignore_index=True)
  f.write(f'{{ "race_data": {races.to_json(orient="records")} }}')
  f.close()

In [18]:
# Asian, 18-29, Male
r = races.loc[races['race'] == 'Hispanic/Latino']
a = ages.loc[ages['age'] == '18-29 Years']
s = sexes.loc[sexes['sex'] == 'Male']

#(r['Case porp'], a['Case porp'], s['Case porp'])
(r['Pop porp']* a['Pop porp'], s['Pop porp'])

(0   NaN
 4   NaN
 Name: Pop porp, dtype: float64,
 1    0.4925
 Name: Pop porp, dtype: float64)

In [23]:
import json
from string import ascii_lowercase as alpha

age_vals = pd.read_csv('data/age_data.csv', header=0, names=['value', 'cases', 'Case count', 'deaths', 'Death count', 'pop', 'dc_ratio'])['value'].values
sex_vals = pd.read_csv('data/sex_data.csv', header=0, names=['value', 'cases', 'Case count', 'deaths', 'Death Range', 'Death count', 'pop', 'dc_ratio'])['value'].values
race_vals = pd.read_csv('data/ethnicity_data.csv', header=0, names=['value', 'cases', 'Case count', 'deaths', 'Death count', 'pop', 'dc_ratio'])['value'].values
vals = [age_vals, sex_vals, race_vals]
labels = ['age','sex', 'race']

a = 0
fields = open('fields.json', 'w+')
fields.write(f'{{"options" :{{\n')
for i, (val, label) in enumerate(zip(vals,labels)):
  fields.write(f'   "{label}" : [\n')
  for v in val:
    fields.write(f'    {{"key" : "{alpha[a]}", "text": "{v}", "value": "{v}"}},\n')
    a += 1
  
  fields.write(f'    {{"key" : "{alpha[a]}", "text": "-", "value": "-"}}\n')
  a += 1
  
  if i == len(labels)-1:
    fields.write('  ]\n')
  else:
    fields.write('  ],\n')
fields.write('}}')
fields.close()

In [41]:
ages

          value   pop      cases     deaths   dc_ratio
0     0-4 Years   6.0   2.586612   0.045436   0.029522
1    5-11 Years   8.7   5.644570   0.030342   0.009030
2   12-15 Years   5.1   4.362699   0.035425   0.013647
3   16-17 Years   2.5   2.751942   0.033423   0.020411
4   18-29 Years  16.4  21.664864   0.719895   0.055845
5   30-39 Years  13.5  16.586421   1.660349   0.168236
6   40-49 Years  12.3  14.483574   3.806636   0.441711
7   50-64 Years  19.2  19.182482  17.029977   1.492045
8   65-74 Years   9.6   7.163820  21.866553   5.129892
9   75-84 Years   4.9   3.627246  26.253541  12.164199
10    85+ Years   2.0   1.945770  28.518423  24.632395
11            -   0.0   0.000000   0.000000   0.000000